---
# Install powerlevel10k
- name: Ensure dependencies are installed.
  package:
    name: "{{ p10k_dependencies }}"
    state: present

- name: Get ZSH version
  shell: "set -o pipefail; zsh --version | cut -d ' ' -f2 | cut -c1-3"
  args:
    executable: /bin/bash
  check_mode: no
  changed_when: false
  register: zsh_version

- name: Powerlevel10k works only with ZSH >= 5.1
  fail:
    msg: "You are using ZSH version {{ zsh_version.stdout }}. The minimum required version for Powerlevel10k is 5.1"
  when: zsh_version.stdout|float < 5.1

- name: Install powerlevel10k.
  git:
    repo: "{{ p10k_repository_url }}"
    dest: "{{ p10k_path[zsh_plugin] | default('~/powerlevel10k', True) }}"
    depth: '1'
    update: no
    version: 'master'
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ p10k_users }}"

- name: Add powerlevel10k to zsh plugin
  lineinfile:
    path: "{{ p10k_zshrc_config[zsh_plugin]['zsh_file'] }}"
    regexp: "{{ p10k_zshrc_config[zsh_plugin]['regexp'] }}"
    line: "{{ p10k_zshrc_config[zsh_plugin]['line'] }}"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
    create: yes
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ p10k_users }}"

- name: Enable powerlevel10 instant prompt
  blockinfile:
    path: "{{ p10k_zshrc_config[zsh_plugin]['zsh_file'] }}"
    block: |
      if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
        source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
      fi
    insertbefore: BOF
    marker_begin: "BEGIN P10K INSTANT PROMPT"
    marker_end: "END P10K INSTANT PROMPT"
